# Generated by Django 4.0.1 on 2022-01-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='email')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_img', verbose_name='picture')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('hobbies', models.CharField(blank=True, max_length=500, verbose_name='hobbies')),
                ('favorite_tv', models.CharField(blank=True, max_length=500, verbose_name='favorite tv')),
                ('favorite_books', models.CharField(blank=True, max_length=500, verbose_name='favorite books')),
                ('work', models.CharField(blank=True, max_length=500, verbose_name='employment')),
                ('schools', models.CharField(blank=True, max_length=500, verbose_name='studies')),
                ('username', models.CharField(max_length=75, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('first_name', 'last_name', 'email'),
            },
        ),
    ]
